// <auto-generated />
using System;
using AirlineBooking.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirlineBooking.Migrations
{
    [DbContext(typeof(AirlineBookingDbContext))]
    [Migration("20220302034300_Ubah_Booking_KodeBooking_5")]
    partial class Ubah_Booking_KodeBooking_5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AirlineBooking.Models.AirportGatewayModel", b =>
                {
                    b.Property<long>("IDGateway")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_gateway");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IDGateway"), 1L, 1);

                    b.Property<string>("KodeAirport")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("kode_airport");

                    b.Property<string>("NomorGate")
                        .IsRequired()
                        .HasColumnType("varchar(5)")
                        .HasColumnName("nomor_gate");

                    b.Property<string>("NomorPintu")
                        .IsRequired()
                        .HasColumnType("varchar(5)")
                        .HasColumnName("nomor_pintu");

                    b.HasKey("IDGateway");

                    b.ToTable("airport_gateway");
                });

            modelBuilder.Entity("AirlineBooking.Models.AirportModel", b =>
                {
                    b.Property<string>("KodeAiport")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("kode_airport");

                    b.Property<string>("Kota")
                        .IsRequired()
                        .HasColumnType("varchar(60)")
                        .HasColumnName("kota");

                    b.Property<string>("NamaAirport")
                        .IsRequired()
                        .HasColumnType("varchar(60)")
                        .HasColumnName("nama_airport");

                    b.Property<string>("Propinsi")
                        .IsRequired()
                        .HasColumnType("varchar(60)")
                        .HasColumnName("propinsi");

                    b.HasKey("KodeAiport");

                    b.ToTable("airport");
                });

            modelBuilder.Entity("AirlineBooking.Models.BookingModel", b =>
                {
                    b.Property<string>("KodeBooking")
                        .HasColumnType("varchar(5)")
                        .HasColumnName("kode_booking");

                    b.Property<int>("BatasBagasi")
                        .HasColumnType("int")
                        .HasColumnName("batas_bagasi");

                    b.Property<int>("BatasBagasiKabin")
                        .HasColumnType("int")
                        .HasColumnName("batas_bagasi_kabin");

                    b.Property<int>("Durasi")
                        .HasColumnType("int")
                        .HasColumnName("durasi");

                    b.Property<decimal>("HargaTiket")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("harga_tiket");

                    b.Property<int>("JumlahPenumpang")
                        .HasColumnType("int")
                        .HasColumnName("jumlah_penumpang");

                    b.Property<string>("KodeAiportTujuan")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("kode_airport_tujuan");

                    b.Property<string>("KodeAirportAsal")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("kode_airport_asal");

                    b.Property<string>("KodeCheckIn")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("kode_check_in");

                    b.Property<string>("KodeMaskapai")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("kode_maskapai");

                    b.Property<string>("KodePembayaran")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("kode_pembayaran");

                    b.Property<string>("KodePenerbangan")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("kode_penerbangan");

                    b.Property<int>("MetodeBayar")
                        .HasColumnType("int")
                        .HasColumnName("metode_bayar");

                    b.Property<string>("NamaAirportAsal")
                        .IsRequired()
                        .HasColumnType("varchar(60)")
                        .HasColumnName("nama_airport_asal");

                    b.Property<string>("NamaAirportTujuan")
                        .IsRequired()
                        .HasColumnType("varchar(60)")
                        .HasColumnName("nama_airport_tujuan");

                    b.Property<string>("NamaMaskapai")
                        .IsRequired()
                        .HasColumnType("varchar(60)")
                        .HasColumnName("nama_maskapai");

                    b.Property<int>("StatusBooking")
                        .HasColumnType("int")
                        .HasColumnName("status_booking");

                    b.Property<DateTime>("TglKeberangkatan")
                        .HasColumnType("datetime")
                        .HasColumnName("tgl_keberangkatan");

                    b.Property<DateTime>("TglKedatangan")
                        .HasColumnType("datetime")
                        .HasColumnName("tgl_kedatangan");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total");

                    b.HasKey("KodeBooking");

                    b.ToTable("booking");
                });

            modelBuilder.Entity("AirlineBooking.Models.BookingPenumpangModel", b =>
                {
                    b.Property<string>("KTP")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("ktp");

                    b.Property<string>("KodeBooking")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("kode_booking");

                    b.Property<string>("NamaPenumpang")
                        .IsRequired()
                        .HasColumnType("varchar(60)")
                        .HasColumnName("nama_penumpang");

                    b.Property<string>("NomorKursi")
                        .IsRequired()
                        .HasColumnType("varchar(5)")
                        .HasColumnName("nomor_kursi");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(3)")
                        .HasColumnName("title");

                    b.HasKey("KTP");

                    b.ToTable("booking_penumpang");
                });

            modelBuilder.Entity("AirlineBooking.Models.JenisPesawatModel", b =>
                {
                    b.Property<string>("KodeJenisPesawat")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("kode_jenis_pesawat");

                    b.Property<int>("TahunPesawat")
                        .HasColumnType("int")
                        .HasColumnName("tahun_pesawat");

                    b.HasKey("KodeJenisPesawat");

                    b.ToTable("jenis_pesawat");
                });

            modelBuilder.Entity("AirlineBooking.Models.KursiPesawatModel", b =>
                {
                    b.Property<string>("IDKursiPesawat")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("id_kursi_pesawat");

                    b.Property<string>("KodePenerbangan")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("kode_penerbangan");

                    b.Property<string>("NomorKursi")
                        .IsRequired()
                        .HasColumnType("varchar(5)")
                        .HasColumnName("nomor_kursi");

                    b.HasKey("IDKursiPesawat");

                    b.ToTable("kursi_pesawat");
                });

            modelBuilder.Entity("AirlineBooking.Models.MaskapaiModel", b =>
                {
                    b.Property<string>("KodeMaskapai")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("kode_maskapai");

                    b.Property<string>("NamaMaskapai")
                        .IsRequired()
                        .HasColumnType("varchar(60)")
                        .HasColumnName("nama_maskapai");

                    b.HasKey("KodeMaskapai");

                    b.ToTable("maskapai");
                });

            modelBuilder.Entity("AirlineBooking.Models.PesawatModel", b =>
                {
                    b.Property<string>("KodePenerbangan")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("kode_penerbangan");

                    b.Property<string>("KodeJenisPesawat")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("kode_jenis_pesawat");

                    b.Property<string>("KodeMaskapai")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("kode_maskapai");

                    b.HasKey("KodePenerbangan");

                    b.ToTable("pesawat");
                });

            modelBuilder.Entity("AirlineBooking.Models.ScheduleModel", b =>
                {
                    b.Property<long>("ScheduleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("schedule_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ScheduleID"), 1L, 1);

                    b.Property<int>("BatasBagasi")
                        .HasColumnType("int")
                        .HasColumnName("batas_bagasi");

                    b.Property<int>("BatasBagasiKabin")
                        .HasColumnType("int")
                        .HasColumnName("batas_bagasi_kabin");

                    b.Property<string>("KodeAirportAsal")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("kode_asal_airport");

                    b.Property<string>("KodeAirportTujuan")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("kode_asal_tujuan");

                    b.Property<string>("KodeMaskapai")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("kode_maskapai");

                    b.Property<string>("KodePenerbangan")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("kode_penerbangan");

                    b.Property<DateTime>("TglKeberangkatan")
                        .HasColumnType("datetime")
                        .HasColumnName("tgl_keberangkatan");

                    b.Property<DateTime>("TglKedatangan")
                        .HasColumnType("datetime")
                        .HasColumnName("tgl_kedatangan");

                    b.HasKey("ScheduleID");

                    b.ToTable("schedule");
                });
#pragma warning restore 612, 618
        }
    }
}
